### ISSUE TITLE
Gene abundances

### ISSUE THREAD

**Issue by ebustos128** [metasnv-tool/metaSNV#1]
Hi,

I have one question about how to use the metaSNV_subpopr.R script. In the manual that you attached there is a section on how to calculate the abundance of genes:

"Gene abundance profiles can be compiled from any valid approach. See the metaSNV v2 paper for an example, where gene abundance profiles were compiled per sample by mapping each sample against a set of species’ pangenomes, selected to reflect the species with subspecies in this study. Briefly, metagenomic reads were mapped against species pangenomes (Maistrenko 2020, https://doi.org/10.1038/s41396-020-0600-z) using BWA (REF) and ngless (Coelho 2019, https://doi.org/10.1186/s40168-019-0684-8). Reads were kept if they mapped uniquely to a gene with a minimum match length of 45bp and minimum percent identity of 97%. Relationships between genes and COG categories were produced by eggNOG5 (Huerta-Cepas 2019, https://doi.org/10.1093/nar/gky1085) and obtained from the pangenomes, with species provenance information maintained. COG category abundances were calculated as sums of their member gene abundances."

If I want to do this analysis, I would need to cluster the genes as Maistrenko 2020 did and after calculate the bam files of these genes?

Thanks,
Esteban

**Comment by theavanrossum** [comment]
Hi Esteban,
I'll answer generally first in case any other users want clarification:
You shouldn't need to do any clustering. You would need to map your reads against some catalog of genes and then use the mapping depth as a measurement of gene abundance. Optionally, you could then summarise gene abundances into functional category abundances (such as KEGG KO abundances or KEGG Module abundances). Doing this is recommended since it greatly reduces the number of features (and thus run time and false positives). In the text above, I use the pangenomes from Maistrenko et al as my catalog of genes. MetaSNV just treats gene abundances as a table of features, so you could even run something like humann2 to get gene abundance profiles and then use those. 

Now specifically for you:
From your email, I understand you want to use a set of MAGs as a custom reference database. If you want to get gene abundances specifically for these MAGs, then yes, I would say you'd want to cluster the predicted genes from your MAGs at a reasonable species threshold (e.g. 97%) then do your mapping and abundance calculations. If you don't cluster first, it might still work, but you might get a lot of noise from conserved genes. As I mentioned above, what ever way you would normally get gene abundances should work. It just needs a table of features vs samples, where the cells are abundances. Here, features could be genes, GOs, KEGG modules, etc.

Hope that helps,
Thea
