### ISSUE TITLE
[mpileup] failed to open: Too many open files

### ISSUE THREAD

**Issue by zhaoc1** [metasnv-tool/metaSNV#5]
Hi,

I am running metaSNV (installed via conda) for ~1000 samples, on ~400 species. 

After the "coverage summary" section:

```
Coverage summary here: /mnt/cz/metasnv_output
	Average vertical genome coverage: '/mnt/cz/metasnv_output/metasnv_output.all_cov.tab'
	Horizontal genome coverage (1X): '/mnt/cz/metasnv_output/metasnv_output.all_perc.tab'
```

I ran into the following errors in the "Calculating best database split" secion:

```
Calculating best database split:
[E::hts_open_format] [E::hts_open_format] [E::hts_open_format] [E::hts_open_format] [E::hts_open_format] [E::hts_open_format] [E::hts_open_format] [E::hts_open_format] Failed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open filesFailed to open file "/mnt/cz/bwa/ERR4341882.bam" : Too many open files
```

Despite the above error message, metaSNV continued running, yet identified 0 samples in the results.

After some googling, it seems like metaSNV exceeds the `ulimit -n`, which is 1024 files per process. Any idea about how to fix this issue?  Thanks.

Chunyu

**Comment by zhaoc1** [comment]
@alimayy Good question. The BAM coverage is not that high, but the warning might be some falsely pileup repeats regions.

**Comment by LucasPaoli** [comment]
Hi both,

The potential memory hog warning is generated by samtools, so not much we can do about it. See https://github.com/samtools/samtools/issues/619 for details.

Indeed it's because there are one or more positions with a coverage higher than the maximum depth of mpileup and the reads above that limit will be dropped. If the reads are in a random order in the bam file then that shouldn't affect the allelic frequency spectrum so it should be safe to ignore. Otherwise, you could look into subsampling the bam file, for instance with `samtools view -s`.

I'll close the issue assuming the main problem is fixed, but let us if you find anything else.

Best, 

Lucas
