### ISSUE TITLE
Question on bam file filtering before running metaSNV2

### ISSUE THREAD

**Issue by hdore** [metasnv-tool/metaSNV#6]
Hello,

Thank you for developing metaSNV! 
I'd like to try it with bam files I obtained by aligning metagenomics reads to a custom reference using bwa-mem. Following metaSNV userguide, I'm trying to filter my BAM files to only "keep mappings with at least 97% identity and 45 bp length, and discard multi-mapped reads" but I'm not 100% sure of what that means. I've looked at the ngless example and at the ngless documentation for the method `filter` but I'm still unclear on how you perform filtering: 

- `min_match_size=45`: should we consider only reads with > 45 "M" in the cigar string (M field, i.e matches + mismatches) or the reads with an alignment length > 45 (fields M+I+D, i.e including insertions and deletions but removing clipped bases)? 

- `min_identity_pc=97`: How is this calculated in ngless? Is it the number of matches (same base as the reference) over the length of the alignment (including matches, mismatches, insertions and deletions), or the number of matches over the total of matches + mismatches (M field of the cigar string, excluding insertions and deletions), or another definition?

Thank you for your help!

hdore

**Comment by LucasPaoli** [comment]
Hi,

Thank you for using metaSNV.

Generally you would have:

- alignment length = MID, so that's correct, you exclude clipped bases.
- percent identity = (MID - NM) / MID (where NM is the edit distance); but you may indeed find variations between different softwares on wether I and D are included or not.

All these computation can be automated using ngless or other alternatives (e.g. https://github.com/arumugamlab/msamtools).

Hope that helps!
