### ISSUE TITLE
Different results from bowtie2 --very-sensitive-local and --very-fast

### ISSUE THREAD

**Issue by alimayy** [metasnv-tool/metaSNV#7]
___
EDIT

Please disregard this issue for now. I think I found out the reason (not metaSNV-related) which I'll describe here soon.
__
Hi there,

When I align a dataset of multiple samples against the same reference gene with bowtie2 using '--very-fast' and '--very-sensitive-local', I am getting very different results from metaSNV. The bowtie commands are:

`bowtie2-align-s -r reads.fastq --very-fast -x <path_to_bowtie_index> --no-unal -p <nr_cpus> -S aln.sam`

and

`bowtie2-align-s -r reads.fastq.gz --very-sensitive-local -x <path_to_bowtie_index> --no-unal -p <nr_cpus -S aln.sam`

an example of the SAM entry they generate, respectively:

--very-fast:
`24070921	0	<ref_name>	563	42	101M	*	0	0	ACGGCAATGAATACAAATGGGCCGGCAAAGATGATAATGGGTATTACTCGGTTATTGATTTAGATAAAAACTATGACCAAGTAGGAGTTTTAATTAAAACC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:101	YT:Z:UU
`

--very-sensitivice-local:
`24070921	0	<ref_name>	563	44	101M	*	0	0	ACGGCAATGAATACAAATGGGCCGGCAAAGATGATAATGGGTATTACTCGGTTATTGATTTAGATAAAAACTATGACCAAGTAGGAGTTTTAATTAAAACC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:202	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:101	YT:Z:UU
`

I use exactly the same metaSNV commands to process the BAM files. The final metaSNV result is that the alignments from --very-fast result in many more (correctly called) SNPs in for the 'ind' SNPs in the file

`<output_folder>/filtered/ind/<ref_name>.filtered.freq `

while most of the correct SNPs are missing in the results generated by --very-sensitive-local. 

SNPs called across the reference with --very-fast:
![image](https://user-images.githubusercontent.com/22055534/150445159-da8d2408-0e26-414a-9971-f2f05303f92b.png)

SNPs called across the reference with --very-sensitive-local:
![image](https://user-images.githubusercontent.com/22055534/150445287-082c9ad5-8f97-4cba-95ee-3de8c9ec236e.png)

The two alignments are near-identical (for all samples) except for the soft-clipped reads from --very-sensitive-local

![image](https://user-images.githubusercontent.com/22055534/150445414-e6caeeae-95de-439b-8c3d-dcc85b1ddeb7.png)

Any clue what may be going on?

**Comment by zhaoc1** [comment]
Hi @alimayy 

I think there are a few potential reasons for this observation.

First, the default bowtie2 aligner is a global alignment.

Second, I think it is s a feature of `samtools mpileup` to filter reads in the BAM file for pileup. I can share a similar observation with yours. I observed that when there is <*> in the VCF file, then samtools would not consider the alternative alleles, and call it a fixed site. 

For example, a straightforward, filtered reads pileup for one genomic site (ref_positive 4576; ref_allele A) is shown as the following  (computed by [MIDAS](https://github.com/czbiohub/iggtools)):

![image](https://user-images.githubusercontent.com/9036669/154559031-a5bc6f97-0ff5-4557-8aaa-575146ce0440.png)

And it is consistent with the unfiltered IGV tools stats:
![image](https://user-images.githubusercontent.com/9036669/154559271-75c94fc2-4797-4b98-8b46-315d93126fa7.png)

However, samtools reported a "false fixed site" G instead of the G/A, and the corresponding row from the VCF file is:

![image](https://user-images.githubusercontent.com/9036669/154559374-98e1109e-7cc6-4d2f-80e1-d3069c4659b0.png)

Also notice the significant different of the site depth (813 in the raw BAM file and only 247 used by samtools for pileup).

Last but not lease, metaSNV only reported the non-reference SNV sites in the report. 

I think all the above reasons might explain why  "the soft-clipped reads from --very-sensitive-local reports few SNPs".

I hope this is helpful!
Chunyu

**Comment by zhaoc1** [comment]
I think this might be a `samtools mpileup` related issue: I observed `mpileup` doens't report variants for sites with unspecified alternate allele (specified as <*>). 

For example, for the following site, `mpileup` would report a fixed allele at G, instead of G/A.

![image](https://user-images.githubusercontent.com/9036669/165456692-792cd550-00c4-4a51-8de6-d118729948c1.png)

I wonder if this can explain the missing SNPs with the local Bowtie2 alignment (--very-sensitive-local).
